# Available drivers: h2, mysql
# If you are using h2, you don't need to specify the host, port, db-name,
# username and password due to h2 is local database.
database:
  driver: h2
  host: 101.101.101.101
  port: 3306
  db-name: hubcombat
  username: userNaMeForHubCombat
  password: passw0rD

timing:
  give-weapon: 5
  remove-weapon: 5

# All the items from plugin
# U can add as many loadouts as u want! Also, u can add as many items
# as u want in the loadouts, just copy and paste the "template" for items
loadouts:
  default:
    permission: hubcombat.loadout.default
    items:
      - slot: 4
        material: DIAMOND_SWORD
        name: "<gray>Default Sword"
        lore:
          - "<white>Basic starter sword"
        enchantments:
          DAMAGE_ALL: 3
          DURABILITY: 2
        flags:
          - HIDE_ENCHANTS
          - HIDE_ATTRIBUTES

  vip:
    permission: hubcombat.loadout.vip
    items:
      - slot: 4
        material: NETHERITE_SWORD
        name: "<green>VIP Sword"
        lore:
          - "<gold>Only for VIPs"
        enchantments:
          DAMAGE_ALL: 5
          KNOCKBACK: 2
