name: HubCombat
version: '1.0.0-SNAPSHOT'
main: dev.smartshub.hubCombat.HubCombat
api-version: '1.21'
authors: [ hhitt ]
softdepend: [PlaceholderAPI]
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.21.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.21.0
